dtcollector:
  container_name: "dtcollector"
  hostname: "docker-dtcollector"
  image: "dynatrace/collector:6.3"
  external_links:
    - dtserver
  environment:
    DT_COLLECTOR_NAME: "dtcollector"
    HOST_NAME: "docker-dtcollector"
  volumes:
    - "/tmp/log/dynatrace/collectors/dtcollector:/dynatrace/log/collector/dtcollector"